const STORAGE_KEY='moneyLeakTracker.v1';
const SETTINGS_KEY='moneyLeakTracker.settings';
const categories=['streaming','software','cloud','mobile','insurance','finance','shopping','education','transport','housing','health','meeting','other'];
const categoryLabels={streaming:'스트리밍',software:'소프트웨어',cloud:'클라우드',mobile:'모바일',insurance:'보험',finance:'금융',shopping:'쇼핑',education:'교육',transport:'교통',housing:'주거',health:'건강',meeting:'모임',other:'기타'};
const cycleLabels={monthly:'월간',yearly:'연간',weekly:'주간',every_3_months:'3개월마다',every_6_months:'6개월마다',custom:'사용자 지정'};
const statusLabels={active:'활성',paused:'일시정지',canceled:'해지'};
const usageLabels={high:'높음',medium:'보통',low:'낮음',unused:'미사용'};
const cycles=Object.keys(cycleLabels), state={expenses:[],settings:{currency:'KRW',darkMode:false},selected:new Set(),calendarWindow:'month'};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function loadData(){state.expenses=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');state.settings={...state.settings,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')};}
function saveData(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.expenses));}
function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(state.settings));}
function monthlyCost(e){const a=Number(e.amount)||0;return {monthly:a,yearly:a/12,weekly:a*52/12,every_3_months:a/3,every_6_months:a/6,custom:a/(Number(e.customCycleMonths)||1)}[e.billingCycle]||0;}
function annualCost(e){return monthlyCost(e)*12;}
function formatCurrency(v){const c=state.settings.currency;const opts={KRW:{symbol:'₩',dec:0},USD:{symbol:'$',dec:2},JPY:{symbol:'¥',dec:0},EUR:{symbol:'€',dec:2}}[c];return opts.symbol+Number(v||0).toLocaleString(undefined,{minimumFractionDigits:opts.dec,maximumFractionDigits:opts.dec});}
function isCandidate(e){return e.status==='active'&&['unused','low'].includes(e.usageLevel)&&Number(e.satisfaction)<=2&&!e.isEssential;}
function activeExpenses(){return state.expenses.filter(e=>e.status==='active');}
function nextPaymentDate(e){const today=new Date();const day=Math.min(Number(e.paymentDay)||1,31);let d=new Date(today.getFullYear(),today.getMonth(),day);if(d<startOfDay(today))d=new Date(today.getFullYear(),today.getMonth()+1,day);return d;}
function startOfDay(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate());}
function daysBetween(a,b){return Math.ceil((startOfDay(b)-startOfDay(a))/86400000);}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);}
function showModal(title,msg,onOk){$('#confirmTitle').textContent=title;$('#confirmMessage').textContent=msg;const d=$('#confirmDialog');const ok=$('#confirmOk');ok.onclick=()=>{d.close();onOk();};$('#confirmCancel').onclick=()=>d.close();d.showModal();}
function renderAll(){document.body.classList.toggle('dark',state.settings.darkMode);$('#darkModeToggle').checked=state.settings.darkMode;$('#currencySelect').value=state.settings.currency;renderDashboard();renderExpenseList();renderCalendar();renderSavings();}
function empty(msg){return `<div class="empty"><p>${msg}</p></div>`;}
function renderDashboard(){const active=activeExpenses(), candidates=active.filter(isCandidate);const monthly=active.reduce((s,e)=>s+monthlyCost(e),0), candidateMonthly=candidates.reduce((s,e)=>s+monthlyCost(e),0);const upcoming=active.sort((a,b)=>nextPaymentDate(a)-nextPaymentDate(b))[0];const cards=[['월 고정비',formatCurrency(monthly),'현재 활성 항목 기준'],['연간 고정비',formatCurrency(monthly*12),'정규화된 연간 비용'],['활성 구독 수',active.length+'개','해지/일시정지 제외'],['다가오는 결제',upcoming?upcoming.name:'없음',upcoming?`${nextPaymentDate(upcoming).getMonth()+1}/${nextPaymentDate(upcoming).getDate()}`:'-'],['잠재 월 절약',formatCurrency(candidateMonthly),'해지 후보 기준'],['잠재 연 절약',formatCurrency(candidateMonthly*12),'해지 후보 기준']];$('#summaryCards').innerHTML=cards.map(c=>`<div class="summary-card"><p>${c[0]}</p><strong>${c[1]}</strong><small>${c[2]}</small></div>`).join('');const byCat={};active.forEach(e=>byCat[e.category]=(byCat[e.category]||0)+monthlyCost(e));const max=Math.max(1,...Object.values(byCat));$('#categorySummary').innerHTML=Object.keys(byCat).length?Object.entries(byCat).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div><b>${categoryLabels[k]}</b><span class="meta"> ${formatCurrency(v)}/월</span><div class="bar"><i style="width:${v/max*100}%"></i></div></div>`).join(''):empty('아직 등록된 활성 고정비가 없습니다.');$('#topExpensive').innerHTML=active.sort((a,b)=>monthlyCost(b)-monthlyCost(a)).slice(0,5).map(itemMini).join('')||empty('비싼 항목을 분석하려면 고정비를 추가하세요.');$('#cancelCandidates').innerHTML=candidates.map(itemMini).join('')||empty('현재 해지 후보가 없습니다.');}
function itemMini(e){return `<div class="payment-card"><div class="card-head"><div><b>${e.name}</b><div class="meta">${categoryLabels[e.category]} · ${cycleLabels[e.billingCycle]}</div></div><span class="amount">${formatCurrency(monthlyCost(e))}</span></div></div>`;}
function applyFilters(list){const q=$('#searchInput').value.toLowerCase(), cat=$('#categoryFilter').value, st=$('#statusFilter').value;return list.filter(e=>(!q||e.name.toLowerCase().includes(q)||(e.memo||'').toLowerCase().includes(q))&&(cat==='all'||e.category===cat)&&(st==='all'||e.status===st));}
function sortExpenses(list){const s=$('#sortSelect').value;return [...list].sort((a,b)=>s==='highest'?monthlyCost(b)-monthlyCost(a):s==='lowest'?monthlyCost(a)-monthlyCost(b):s==='nearest'?nextPaymentDate(a)-nextPaymentDate(b):s==='name'?a.name.localeCompare(b.name):new Date(b.createdAt)-new Date(a.createdAt));}
function renderExpenseList(){const list=sortExpenses(applyFilters(state.expenses));$('#expenseList').innerHTML=list.map(expenseCard).join('')||empty('등록된 고정비가 없습니다. 첫 항목을 추가해 보세요.');bindExpenseActions();}
function expenseCard(e){return `<article class="expense-card"><div class="card-head"><div><h3>${e.name}</h3><div class="meta">${categoryLabels[e.category]} · ${formatCurrency(e.amount)} / ${cycleLabels[e.billingCycle]}</div></div><span class="amount">${formatCurrency(monthlyCost(e))}/월</span></div><div class="badges"><span class="badge ${e.status==='active'?'ok':e.status==='canceled'?'danger':''}">${statusLabels[e.status]}</span><span class="badge">${usageLabels[e.usageLevel]}</span><span class="badge">만족도 ${e.satisfaction}</span>${e.isEssential?'<span class="badge ok">필수</span>':''}${isCandidate(e)?'<span class="badge warn">해지 후보</span>':''}</div><p class="meta">연 ${formatCurrency(annualCost(e))} · 매월 ${e.paymentDay}일 결제</p>${e.memo?`<p>${e.memo.slice(0,90)}</p>`:''}<div class="actions"><button data-edit="${e.id}">수정</button><button data-status="${e.id}" data-next="active">활성</button><button data-status="${e.id}" data-next="paused">일시정지</button><button data-status="${e.id}" data-next="canceled">해지</button><button class="danger" data-delete="${e.id}">삭제</button></div></article>`;}
function renderCalendar(){const today=new Date(), endMonth=new Date(today.getFullYear(),today.getMonth()+1,0);let rows=activeExpenses().map(e=>({...e,due:nextPaymentDate(e),days:daysBetween(today,nextPaymentDate(e))}));if(state.calendarWindow==='7')rows=rows.filter(e=>e.days<=7);else if(state.calendarWindow==='30')rows=rows.filter(e=>e.days<=30);else if(state.calendarWindow==='month')rows=rows.filter(e=>e.due<=endMonth);else rows=activeExpenses().filter(e=>Number(e.paymentDay)<today.getDate()).map(e=>({...e,due:new Date(today.getFullYear(),today.getMonth(),e.paymentDay),days:daysBetween(today,new Date(today.getFullYear(),today.getMonth(),e.paymentDay))}));rows.sort((a,b)=>a.due-b.due);$('#calendarList').innerHTML=rows.map(e=>`<article class="payment-card"><div class="card-head"><div><h3>${e.name}</h3><div class="meta">${categoryLabels[e.category]} · ${e.due.toLocaleDateString('ko-KR')}</div></div><span class="amount">${formatCurrency(e.amount)}</span></div><span class="badge ${e.days<0?'danger':e.days<=7?'warn':''}">${e.days<0?Math.abs(e.days)+'일 지남':e.days+'일 남음'}</span></article>`).join('')||empty('표시할 예정 결제가 없습니다.');}
function renderSavings(){const selected=activeExpenses().filter(e=>state.selected.has(e.id)), m=selected.reduce((s,e)=>s+monthlyCost(e),0);$('#savingsSummary').innerHTML=[['선택 수',selected.length+'개'],['월 절약',formatCurrency(m)],['연 절약',formatCurrency(m*12)]].map(c=>`<div class="summary-card"><p>${c[0]}</p><strong>${c[1]}</strong></div>`).join('');$('#savingsList').innerHTML=activeExpenses().map(e=>`<label class="expense-card"><span class="card-head"><span><b>${e.name}</b><span class="meta"><br>${categoryLabels[e.category]} · 만족도 ${e.satisfaction}</span></span><input type="checkbox" data-save="${e.id}" ${state.selected.has(e.id)?'checked':''}></span><span class="amount">${formatCurrency(monthlyCost(e))}/월</span></label>`).join('')||empty('활성 고정비가 없습니다.');$$('[data-save]').forEach(i=>i.onchange=()=>{i.checked?state.selected.add(i.dataset.save):state.selected.delete(i.dataset.save);renderSavings();});}
function openForm(e=null){$('#expenseForm').reset();$('#expenseId').value=e?.id||'';$('#formTitle').textContent=e?'고정비 수정':'고정비 추가';$('#startDate').value=new Date().toISOString().slice(0,10);if(e)Object.keys(e).forEach(k=>{const el=$('#'+k);if(el)el.type==='checkbox'?el.checked=e[k]:el.value=e[k];});toggleCustom();$('#expenseDialog').showModal();}
function saveExpense(){const e={id:$('#expenseId').value||crypto.randomUUID(),name:$('#name').value.trim(),amount:Number($('#amount').value),billingCycle:$('#billingCycle').value,customCycleMonths:Number($('#customCycleMonths').value)||1,category:$('#category').value,paymentDay:Number($('#paymentDay').value),startDate:$('#startDate').value,status:$('#status').value,usageLevel:$('#usageLevel').value,satisfaction:Number($('#satisfaction').value),isEssential:$('#isEssential').checked,memo:$('#memo').value.trim(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};if(!e.name||e.amount<=0||e.paymentDay<1||e.paymentDay>31||(e.billingCycle==='custom'&&e.customCycleMonths<=0)){showToast('입력값을 확인해 주세요.');return;}const idx=state.expenses.findIndex(x=>x.id===e.id);if(idx>=0){e.createdAt=state.expenses[idx].createdAt;state.expenses[idx]=e}else state.expenses.push(e);saveData();$('#expenseDialog').close();showToast('저장했습니다.');renderAll();}
function deleteExpense(id){showModal('삭제 확인','이 고정비를 삭제할까요?',()=>{state.expenses=state.expenses.filter(e=>e.id!==id);state.selected.delete(id);saveData();showToast('삭제했습니다.');renderAll();});}
function exportData(){const blob=new Blob([JSON.stringify({expenses:state.expenses,settings:state.settings},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='money-leak-tracker.json';a.click();URL.revokeObjectURL(a.href);}
function validateImport(data){return data&&Array.isArray(data.expenses)&&data.expenses.every(e=>e.id&&e.name&&Number(e.amount)>0&&cycles.includes(e.billingCycle)&&categories.includes(e.category)&&Number(e.paymentDay)>=1&&Number(e.paymentDay)<=31);}
function importData(file){const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!validateImport(data))throw Error();showModal('가져오기 확인','현재 데이터를 가져온 JSON으로 교체할까요?',()=>{state.expenses=data.expenses;state.settings={...state.settings,...(data.settings||{})};saveData();saveSettings();showToast('가져왔습니다.');renderAll();});}catch{showToast('유효한 JSON 데이터가 아닙니다.');}};r.readAsText(file);}
function bindExpenseActions(){$$('[data-edit]').forEach(b=>b.onclick=()=>openForm(state.expenses.find(e=>e.id===b.dataset.edit)));$$('[data-delete]').forEach(b=>b.onclick=()=>deleteExpense(b.dataset.delete));$$('[data-status]').forEach(b=>b.onclick=()=>{const e=state.expenses.find(x=>x.id===b.dataset.status);e.status=b.dataset.next;e.updatedAt=new Date().toISOString();saveData();renderAll();});}
function initOptions(){const cat='<option value="all">전체 카테고리</option>'+categories.map(c=>`<option value="${c}">${categoryLabels[c]}</option>`).join('');$('#categoryFilter').innerHTML=cat;$('#category').innerHTML=categories.map(c=>`<option value="${c}">${categoryLabels[c]}</option>`).join('');$('#billingCycle').innerHTML=cycles.map(c=>`<option value="${c}">${cycleLabels[c]}</option>`).join('');}
function toggleCustom(){$('#customCycleWrap').classList.toggle('hidden',$('#billingCycle').value!=='custom');}
function init(){initOptions();loadData();renderAll();$$('.bottom-nav button').forEach(b=>b.onclick=()=>{$$('.bottom-nav button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active');});$('#quickAddBtn').onclick=$('#addExpenseBtn').onclick=()=>openForm();$$('.close-dialog').forEach(b=>b.onclick=()=>$('#expenseDialog').close());$('#expenseForm').onsubmit=e=>{e.preventDefault();saveExpense();};$('#billingCycle').onchange=toggleCustom;['searchInput','categoryFilter','statusFilter','sortSelect'].forEach(id=>$('#'+id).oninput=renderExpenseList);$$('.calendar-tabs button').forEach(b=>b.onclick=()=>{$$('.calendar-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.calendarWindow=b.dataset.window;renderCalendar();});$$('[data-select]').forEach(b=>b.onclick=()=>{const v=b.dataset.select;if(v==='clear')state.selected.clear();else activeExpenses().filter(e=>v==='unused'?e.usageLevel==='unused':v==='low'?Number(e.satisfaction)<=2:!e.isEssential).forEach(e=>state.selected.add(e.id));renderSavings();});$('#cancelSelectedBtn').onclick=()=>state.selected.size&&showModal('해지 처리 확인',`${state.selected.size}개 항목을 해지 상태로 변경할까요?`,()=>{state.expenses.forEach(e=>{if(state.selected.has(e.id))e.status='canceled'});state.selected.clear();saveData();renderAll();showToast('해지 상태로 변경했습니다.');});$('#darkModeToggle').onchange=e=>{state.settings.darkMode=e.target.checked;saveSettings();renderAll();};$('#currencySelect').onchange=e=>{state.settings.currency=e.target.value;saveSettings();renderAll();};$('#exportBtn').onclick=exportData;$('#importInput').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$('#resetBtn').onclick=()=>showModal('초기화 확인','모든 데이터를 삭제할까요? 되돌릴 수 없습니다.',()=>{state.expenses=[];state.selected.clear();saveData();renderAll();showToast('초기화했습니다.');});}
document.addEventListener('DOMContentLoaded',init);
